language: objective-c
node_js:
  - "0.10"
before_install:
  # Install phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip
  - unzip phantomjs-2.0.0-macosx.zip
  - export PATH="`pwd`/phantomjs-2.0.0-macosx/bin:${PATH}"
  # Run Arunoda's script
  - "curl -L http://git.io/ejPSng | /bin/sh"
script: "make test"
